apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: datapower
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: datapower
    spec:
      containers:
      - image: datapower-playground/datapower:1.0.0
        name: datapower
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
