apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: monitor
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: monitor
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: datapower-playground/monitor:1.0.0
        name: monitor
        resources: {}
      restartPolicy: Always
status: {}
