apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.type: nodeport
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  ports:
  - name: "6001"
    port: 6001
    protocol: TCP
    targetPort: 6001
  selector:
    service: web
  type: NodePort
status:
  loadBalancer: {}
